#!/bin/bash

SCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
cd $SCRIPTPATH/../src/generated

# "$(git rev-parse HEAD)$(test $(git status --porcelain | wc -l) -gt 0 && printf -- -dirty)"
GIT_HASH=$(git rev-parse HEAD)
GIT_DIRTY=$(git status --porcelain | wc -l)

if [ $GIT_DIRTY -ne 0 ]; then
    GIT_HASH="${GIT_HASH}-dirty"
fi

echo '// This file is automatically generated. DO NOT CHANGE!' > version_info.cpp
echo '' >> version_info.cpp
echo '#include "version_info.hpp"' >> version_info.cpp
echo '' >> version_info.cpp
echo 'const std::string version_info::VERSION_STR(PROJECT_VERSION);' >> version_info.cpp
echo 'const std::string version_info::NAME(PROJECT_NAME);' >> version_info.cpp
echo 'const std::string version_info::COMPILER(COMPILER_INFO);' >> version_info.cpp
echo 'const std::string version_info::SYSTEM(SYSTEM_INFO);' >> version_info.cpp
echo "const std::string version_info::GIT_HASH(\"${GIT_HASH}\");" >> version_info.cpp
